name: Test

on:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Generate Typechain artifacts
      - name: Run Typechain
        run: yarn typechain

      # Solhint and Prettier must be in `package.json`
      - name: Run Solhint
        run: yarn lint

      - name: Run Prettier
        run: yarn prettier:check

      - name: Run Unit test and coverage
        run: yarn coverage
        